#!/usr/bin/env python3
"""Regenerate tulip/fs/tulip/jdic.z, the kana-to-kanji dictionary the IME uses.

    python3 tulip/shared/gen_jdict.py            # rebuild the committed file
    python3 tulip/shared/gen_jdict.py --check    # verify it matches, write nothing

Downloads about 60MB from GitHub and takes a minute or two.

WHERE THE DATA COMES FROM, AND WHY THIS SOURCE

The obvious choice for a Japanese input dictionary is SKK-JISYO, which is small
and purpose-built -- SKK-JISYO.S is 3379 readings in 56KB. It is GPL, and Tulip
is MIT, so it is not an option here.

The mozc OSS dictionary is BSD-3-Clause and its vocabulary is IPAdic, whose
license permits use, reproduction and distribution with attribution. Neither is
copyleft. It is not shaped like an input dictionary though: it is a morphological
analyser's lexicon, ten files and 60MB of `reading, left-id, right-id, cost,
surface` rows, 1.29 million of them. This script turns it into what a kana-to-
kanji converter actually needs -- reading to candidate surfaces, ordered best
first -- and throws away the rest.

WHAT GETS THROWN AWAY

  - Rows where the surface equals the reading, or equals the reading transposed
    to katakana. Both are conversions the IME does mechanically, and together
    they are a third of the input.
  - Rows above a cost cutoff. mozc's cost is roughly -log(probability), so a
    cutoff is a frequency floor. Without one the dictionary is 21MB: 547k
    readings, almost all of them rare proper nouns and katakana web words.
  - All but the five cheapest surfaces per reading. Candidate six onwards is
    never what anyone wanted, and the tail is most of the bytes.
  - Proper nouns above a tighter cutoff of their own. 固有名詞 is 300k of the
    rows -- mostly surnames and place names nobody types -- but the common ones
    are typed constantly, so they get a lower ceiling rather than a ban.

The result is 59073 readings, 1.8MB of text, 501KB deflated, which fits the ~1MB
free in the 3MB `system` partition with room to spare. For scale, that is more
readings than SKK-JISYO.ML.

FORMAT

A 17-byte plain header, then one zlib stream:

    JDIC1 0001905499\n<zlib stream>

The number is the decompressed length, and it is outside the compressed data
because that is the only place it is useful. MicroPython's deflate.read() with no
size argument grows its result as it goes and takes 16.5s on this file; the same
data readinto() a bytearray of known size takes 2.0s, measured on a Tab5. The
header is what makes the size knowable.

Inside the stream: `;;` header lines, then one entry per line:

    よみ /候補1/候補2/.../

sorted by reading in UTF-8 byte order, so ime.py can binary search the
decompressed buffer without building an index of 59073 offsets in RAM.
"""

import argparse
import collections
import os
import sys
import urllib.request
import zlib

# Pinned rather than tracked to master: this is committed generated data, and a
# dictionary that changes under you makes --check meaningless.
MOZC_COMMIT = "8be758dcc2330011d052a670b39cf8ffbaa1c253"
RAW = ("https://raw.githubusercontent.com/google/mozc/%s/src/data/dictionary_oss/%s")
FILES = ["dictionary%02d.txt" % i for i in range(10)] + ["id.def"]

# Cost ceilings, in mozc's units. See "WHAT GETS THROWN AWAY" above.
COST_MAX = 5300
PROPER_COST_MAX = 4600
MAX_CANDIDATES = 5

# A folder of its own because fs_create.py only walks subdirectories of
# fs/tulip -- a file at that root never reaches the device.
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   "..", "fs", "tulip", "ime", "jdic.z")

# "JDIC1 " + 10 digits + newline.
HEADER_LEN = 17

HEADER = """\
;;Generated by tulip/shared/gen_jdict.py -- do not edit. Sorted by reading in
;;UTF-8 byte order; ime.py binary searches this buffer directly.
;;
;;Built from the Google mozc OSS dictionary, src/data/dictionary_oss at commit
;;{commit}, which is BSD-3-Clause:
;;
;;  Copyright 2010-2018, Google Inc. All rights reserved.
;;  Redistribution and use in source and binary forms, with or without
;;  modification, are permitted provided that the conditions of the
;;  BSD 3-Clause License are met. See https://github.com/google/mozc.
;;
;;The vocabulary is IPAdic (mecab-ipadic-2.7.0-20070801):
;;
;;  Copyright 2000, 2001, 2002, 2003 Nara Institute of Science and Technology.
;;  All Rights Reserved. Use, reproduction, and distribution of this software
;;  is permitted. Any copy of this software, whether in its original form or
;;  modified, must include both the above copyright notice and the following
;;  paragraphs. NAIST disclaims all warranties with regard to this software,
;;  including all implied warranties of merchantability and fitness. A large
;;  portion of the dictionary entries originate from ICOT Free Software.
;;
;;Named entities are enriched from the Okinawa Dictionary
;;(http://sourceforge.jp/projects/o-dic/). Neither source is copyleft, which is
;;why this file can be committed to an MIT-licensed tree at all -- SKK-JISYO,
;;the obvious alternative, is GPL.
"""


def to_katakana(s):
    return ''.join(chr(ord(c) + 0x60) if 0x3041 <= ord(c) <= 0x3096 else c
                   for c in s)


def fetch(name, cache):
    path = os.path.join(cache, name)
    if os.path.exists(path):
        return open(path, 'rb').read()
    data = urllib.request.urlopen(RAW % (MOZC_COMMIT, name)).read()
    os.makedirs(cache, exist_ok=True)
    open(path, 'wb').write(data)
    return data


def render(cache):
    # left-id -> part of speech, so 固有名詞 can be told from everything else.
    pos = {}
    for line in fetch("id.def", cache).decode('utf-8').splitlines():
        p = line.split()
        if len(p) >= 2:
            pos[int(p[0])] = p[1]

    best = collections.defaultdict(dict)
    rows = 0
    for i in range(10):
        name = "dictionary%02d.txt" % i
        for line in fetch(name, cache).decode('utf-8').splitlines():
            p = line.split('\t')
            if len(p) != 5:
                continue
            reading, lid, cost, surface = p[0], int(p[1]), int(p[3]), p[4]
            rows += 1
            if surface == reading or surface == to_katakana(reading):
                continue
            limit = (PROPER_COST_MAX if '固有名詞' in pos.get(lid, '')
                     else COST_MAX)
            if cost > limit:
                continue
            slot = best[reading]
            if surface not in slot or cost < slot[surface]:
                slot[surface] = cost

    lines = []
    for reading in sorted(best):
        ranked = sorted(best[reading].items(), key=lambda kv: kv[1])
        surfaces = [s for s, _ in ranked[:MAX_CANDIDATES]]
        lines.append("%s /%s/\n" % (reading, '/'.join(surfaces)))

    body = ''.join(lines)
    text = HEADER.format(commit=MOZC_COMMIT[:12]) + body
    return text.encode('utf-8'), rows, len(best)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="compare against the committed file instead of writing it")
    ap.add_argument("--cache", default=os.path.join(os.path.dirname(OUT), ".mozc-cache"),
                    help="where to keep the downloaded mozc files")
    args = ap.parse_args()

    text, rows, readings = render(args.cache)
    # See FORMAT above: the decompressed length, outside the compressed data.
    blob = b"JDIC1 %010d\n" % len(text) + zlib.compress(text, 9)

    if args.check:
        try:
            committed = open(OUT, 'rb').read()
            have = zlib.decompress(committed[HEADER_LEN:])
        except Exception as e:
            print("cannot read %s: %s" % (OUT, e), file=sys.stderr)
            return 1
        if have == text:
            print("jdic.z is up to date (%d readings)" % readings)
            return 0
        # Compare the contents, not the compressed bytes: zlib output is not
        # stable across zlib versions and a byte diff would fail spuriously.
        print("jdic.z is stale: %d bytes committed vs %d generated"
              % (len(have), len(text)), file=sys.stderr)
        return 1

    open(OUT, 'wb').write(blob)
    print("wrote %s" % os.path.normpath(OUT))
    print("  %d mozc rows -> %d readings, %d bytes of text, %d deflated"
          % (rows, readings, len(text), len(blob)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
