#!/usr/bin/env python3
"""Regenerate tulip/shared/u8fontdata_jp.c from u8g2's efont Japanese font.

The Japanese face is not carried in u8fontdata.c with the ASCII ones because it
is two orders of magnitude bigger than any of them and it is fetched, not hand
edited. Run this from anywhere:

    python3 tulip/shared/gen_jp_font.py

Pass --check to verify the committed file matches what upstream would produce
now, without writing anything.

Which font, and why this one: u8g2_font_b16_t_japanese3 is efont Biwidth 16 --
one design covering halfwidth Latin at 8x16 and fullwidth Japanese at 16x16, so
the two halves of a mixed line share a box, a baseline and a 1px stroke instead
of being two fonts glued together. efont descends from the 東雲 (Shinonome)
bitmap fonts and is public domain.

The smaller cuts are a trap: japanese1 (47KB) and japanese2 (88KB) both carry
hiragana, katakana and the 常用漢字, but neither has U+3001 、 or U+3002 。 --
verified by probing the fonts, not by reading the docs -- so neither can set an
ordinary Japanese sentence. japanese3 (157KB) is the smallest usable cut.
"""

import argparse
import difflib
import os
import sys
import urllib.request

FONT = "u8g2_font_b16_t_japanese3"
URL = ("https://raw.githubusercontent.com/olikraus/u8g2/master/tools/font/"
       "build/single_font_files/%s.c" % FONT)
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "u8fontdata_jp.c")

PREAMBLE = '''// u8fontdata_jp.c
//
// The Japanese face, and the only font in the tree that is not ASCII-only.
// Generated by tulip/shared/gen_jp_font.py from u8g2's own copy of the efont
// bitmap fonts; see that script for the source URL and how to refresh it.
//
// Why this font and not another: it is "Biwidth", meaning the halfwidth Latin
// and the fullwidth Japanese are one design by one hand, at one 16px box, with
// one 1px stroke -- 'A' advances 8px and 'あ' advances exactly 16. Mixing Latin
// out of font_8x12_r with kanji from somewhere else does not come out even; this
// does, by construction. efont descends from the 東雲 (Shinonome) fonts and is
// public domain.
//
// japanese1 (47KB) and japanese2 (88KB) are smaller cuts of the same face and
// both LOOK sufficient -- they carry all of hiragana, katakana and the 常用漢字.
// They are not: neither one has U+3001 、 or U+3002 。, so no ordinary Japanese
// sentence can be set in them. japanese3 is the smallest cut that can.
//
// Upstream's #ifdef U8G2_USE_LARGE_FONTS guard is deliberately not carried over.
// That macro comes from a platform sniff in u8fontdata.h which does not name
// every Tulip target, and where the sniff misses, the guard turns a 157KB font
// into an undefined symbol at link time rather than anything readable. What does
// gate the array is TULIP_JP_FONT, which names the boards that have room for it
// -- see u8fontdata.h.

#include "u8fontdata.h"

#if defined(TULIP_JP_FONT)

'''.encode("utf-8")

GUARD = b"#ifdef U8G2_USE_LARGE_FONTS"
GUARD_END = b"#endif /* U8G2_USE_LARGE_FONTS */"


def render():
    # Bytes, not str, all the way through: the preamble is UTF-8 Japanese and the
    # font body is a C string literal that may carry raw high bytes, so there is
    # no one codec that round-trips both.
    src = urllib.request.urlopen(URL).read()
    if src.count(GUARD) != 1:
        sys.exit("upstream %s no longer wraps the array in %s" % (FONT, GUARD))
    header, body = src.split(GUARD, 1)
    if not body.rstrip().endswith(GUARD_END):
        sys.exit("upstream %s does not end with %s" % (FONT, GUARD_END))
    body = body.rstrip()[: -len(GUARD_END)].strip(b"\n")
    return (PREAMBLE + header.strip(b"\n") + b"\n" + body + b"\n"
            + b"\n#endif /* TULIP_JP_FONT */\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="compare against the committed file instead of writing it")
    args = ap.parse_args()

    want = render()
    if args.check:
        have = open(OUT, "rb").read()
        if have == want:
            print("%s is up to date" % os.path.basename(OUT))
            return 0
        # The body is one enormous string literal, so report which hunks differ
        # rather than printing a diff of it.
        diff = [l for l in difflib.diff_bytes(
            difflib.unified_diff, have.splitlines(), want.splitlines(),
            lineterm=b"", n=0) if l.startswith(b"@@")]
        print("%s is stale (%d hunk(s) differ); rerun without --check"
              % (os.path.basename(OUT), len(diff)), file=sys.stderr)
        return 1

    with open(OUT, "wb") as f:
        f.write(want)
    print("wrote %s (%d bytes)" % (OUT, len(want)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
